import '@/parsers/ArrayParser';
import '@/parsers/BooleanParser';
import '@/parsers/EnumParser';
import '@/parsers/IntegerParser';
import '@/parsers/ListParser';
import '@/parsers/NullParser';
import '@/parsers/NumberParser';
import '@/parsers/ObjectParser';
import '@/parsers/StringParser';
